### ISSUE TITLE
SetMinimumBackgroundFetchInterval: Unit of minimumBackgroundFetchInterval parameter

### ISSUE THREAD

**Issue by markuspalme** [xamarin/apple-api-docs#136]
The documentation does not state the **unit** of the `minimumBackgroundFetchInterval` parameter. It's a double which does not provide a clue about what's expected (minutes? hours?).

How about adding a `TimeSpan` overload? The native iOS API (https://developer.apple.com/documentation/uikit/uiapplication/1623100-setminimumbackgroundfetchinterva) accepts a `TimeInterval` .

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a1ec67d3-948e-08d1-dc26-bd77571f052d
* Version Independent ID: 1c029bcc-f7df-db30-1bc8-19e073a22b8d
* Content: [UIApplication.SetMinimumBackgroundFetchInterval(Double) Method (UIKit)](https://docs.microsoft.com/de-de/dotnet/api/uikit.uiapplication.setminimumbackgroundfetchinterval?view=xamarin-ios-sdk-12#feedback)
* Content Source: [en/UIKit/UIApplication.xml](https://github.com/xamarin/apple-api-docs/blob/master/en/UIKit/UIApplication.xml)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by conceptdev** [comment]
Thanks for the feedback @markuspalme -- mentioning the unit of measure in the docs is a good idea.

The suggestion of a new overload would be better made in the [open source code repo for Xamarin.iOS](https://github.com/xamarin/xamarin-macios).

**Comment by dalexsoto** [comment]
Thank you for your feedback! The API is already marked as deprecated so it should not be used anymore.
