### ISSUE TITLE
Missing documentation on PreTestAttribute class

### ISSUE THREAD

**Issue by xtu** [xamarin/apple-api-docs#138]
There is no useful information on this page.

---
#### Document Details

<span class="emoji-outer emoji-sizer"><span class="emoji-inner" style="background: url(chrome-extension://immhpnclomdloikkpcefncmfgjbkojmh/emoji-data/sheet_apple_32.png);background-position:95.94594594594594% 75.96944770857814%;background-size:5418.75% 5418.75%" data-codepoints="26a0-fe0f"></span></span> *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 381e4b66-2224-8d7a-76cc-d325373ff293
* Version Independent ID: 85994617-a354-a0e0-2536-ddc23fa9f6cf
* Content: [PreTestAttribute Class (NUnit.Framework)](https://docs.microsoft.com/en-us/dotnet/api/nunit.framework.pretestattribute?view=xamarin-ios-sdk-12)
* Content Source: [en/NUnit.Framework/PreTestAttribute.xml](https://github.com/xamarin/apple-api-docs/blob/master/en/NUnit.Framework/PreTestAttribute.xml)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by underscoreanuj** [comment]
Can I work on this?

**Comment by dalexsoto** [comment]
Hello, while this is a documentation issue, nunit is an external component maintained on it's own repository so I would suggest looking for docs at the source repo instead https://github.com/nunit/nunit thank you!!
