### ISSUE TITLE
Integer or floating point?

### ISSUE THREAD

**Issue by alataffective** [xamarin/apple-api-docs#141]
This is an integer data type but the remarks talk about floating point. Presumably copy paste error from nfloat.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a219754d-aeb4-d06c-4e59-b514199f3cab
* Version Independent ID: 4660e426-e3d9-3324-1947-65643c1812f3
* Content: [nint Struct (System)](https://docs.microsoft.com/en-us/dotnet/api/system.nint?view=xamarin-ios-sdk-12#feedback)
* Content Source: [en/System/nint.xml](https://github.com/xamarin/apple-api-docs/blob/master/en/System/nint.xml)
* Product: **xamarin**
* Technology: **xamarin-ios**
* GitHub Login: @dotnet-bot
* Microsoft Alias: **dotnetcontent**

**Comment by lobrien** [comment]
Thanks for the catch!
