### ISSUE TITLE
CADisplayLink code formatting issue

### ISSUE THREAD

**Issue by HankiDesign** [xamarin/apple-api-docs#147]
The code block on the [CADisplayLink](https://docs.microsoft.com/en-us/dotnet/api/coreanimation.cadisplaylink?view=xamarin-ios-sdk-12) page doesn't have a proper indentation. I can see that it's there in the markdown but for some reason, it doesn't render correctly.

**Docs page:**
![Screenshot 2019-06-22 at 13 07 45](https://user-images.githubusercontent.com/1816448/59963105-cb924980-94ee-11e9-938e-3f67ccf5d401.png)

**Markdown:**
![Screenshot 2019-06-22 at 13 08 47](https://user-images.githubusercontent.com/1816448/59963109-e4026400-94ee-11e9-8b6f-9c05b05daea0.png)

**Comment by lobrien** [comment]
This is a head-scratcher. The XML looks good, the `lang` attribute has the proper value, the `CDATA` looks right... I've posted a question to internal support.

**Comment by dalexsoto** [comment]
Since this issue is about the site experience itself you can file an issue at https://aka.ms/sitefeedback Thank you!
