### ISSUE TITLE
Code block issue

### ISSUE THREAD

**Issue by HankiDesign** [xamarin/apple-api-docs#150]
I just noticed that on the [LinkerSafeAttribute Class](https://docs.microsoft.com/en-us/dotnet/api/foundation.linkersafeattribute?view=xamarin-ios-sdk-12) page, the two bottom code blocks don't format correctly. 

Both have a lot of empty space on the top and the second one doesn't format the third code line correctly. Basically, it's inside a code block but the styling is the same as for an inline code block:

![Formatting issue](https://user-images.githubusercontent.com/1816448/61324963-eddc6600-a813-11e9-9268-93cb97af1643.png)

Here's also the markdown that produces the above picture:

![Markdown](https://user-images.githubusercontent.com/1816448/61325033-16646000-a814-11e9-8ce8-f8242673ce7d.png)

I don't see anything wrong there, just like in the earlier issue #147 I reported.

**Comment by dalexsoto** [comment]
Since this issue is about the site experience itself you can file an issue at https://aka.ms/sitefeedback
