### ISSUE TITLE
DidReceiveRemoteNotification

### ISSUE THREAD

**Issue by cybvitthal** [xamarin/apple-api-docs#151]
"Use 'UNUserNotificationCenterDelegate.WillPresentNotification/DidReceiveNotificationResponse' for user visible notifications and 'ReceivedRemoteNotification' for silent remote notifications."

should be replaced by

"Use 'UNUserNotificationCenterDelegate.WillPresentNotification/DidReceiveNotificationResponse' for user visible notifications and 'DidReceiveRemoteNotification' for silent remote notifications."

**Comment by dalexsoto** [comment]
The statement is correct, `ReceivedRemoteNotification ` refers to `UIApplicationDelegate`'s member
