### ISSUE TITLE
Garbage collection in ReceivedRemoteNotification

### ISSUE THREAD

**Issue by breyed** [xamarin/apple-api-docs#170]
[ReceivedRemoteNotification](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplicationdelegate.receivedremotenotification?view=xamarin-ios-sdk-12) should include guidance as to whether the developer's code should call `GC.Collect`. Is it called automatically by the Xamarin.iOS framework? Does it typically need to be called at all?

**Comment by rolfbjarne** [comment]
Xamarin.iOS will handle garbage collection, there's no need for user code to do it.

**Comment by breyed** [comment]
Thanks. Should the `ReceivedRemoteNotification` docs be updated so that people don't need to find this Github issue to understand the behavior?

**Comment by rolfbjarne** [comment]
What's different between this method and any other method? Why do you think you might need to call GC.Collect in this method?

**Comment by breyed** [comment]
Sorry. Copy and paste typo. I meant [ReceiveMemoryWarning](https://docs.microsoft.com/en-us/dotnet/api/uikit.uiapplicationdelegate.receivememorywarning). I can see how you were wondering why I had submitted the issue. :-)

**Comment by rolfbjarne** [comment]
Ah, that makes much more sense!

The answer is that we call GC.Collect in this case, the developer does not have to.

I've created a PR to add this to the documentation (https://github.com/xamarin/apple-api-docs/pull/171).
