### ISSUE TITLE
CLLocationManager doesn't document accuracy authorization

### ISSUE THREAD

**Issue by breyed** [xamarin/apple-api-docs#201]
iOS 14 added [accuracyAuthorization](https://developer.apple.com/documentation/corelocation/cllocationmanager/3600215-accuracyauthorization) and [locationManagerDidChangeAuthorization(_:)](https://developer.apple.com/documentation/corelocation/cllocationmanagerdelegate/3563956-locationmanagerdidchangeauthoriz). The Xamarin.iOS [CLLocationManager](https://docs.microsoft.com/en-us/dotnet/api/corelocation.cllocationmanager?view=xamarin-ios-sdk-12) has some new members that seem to correlate, but they are undocumented, both in their XML comments and in the online docs. The online docs only describes the prior authorization API, which is now deprecated but still required for compatibility.

**Comment by dalexsoto** [comment]
Thanks for your report!
